### ISSUE TITLE
Performance demo on jsbin no longer works

### ISSUE THREAD

**Issue by 4ver** [brianmhunt/knockout-fast-foreach#14] opened 2015-02-12 15:00 UTC
I'm getting the same error with the latest version. If I revert to https://github.com/brianmhunt/knockout-fast-foreach/commit/ce7a29ee9896f6a2a148a9fe9f5dbe955c8d9766 it's okay.

```
knockout-min.js:63 Uncaught TypeError: Unable to process binding "fastForEach: function (){return {data:list,afterQueueFlush:afterQueueFlush} }"
Message: undefined is not a function
```

http://jsbin.com/heteca/6

Cheers.

**Comment by brianmhunt** [comment] 2015-02-12 15:48
Thanks @4ver – the problem is #13, namely that I have not yet copied over some private KO functionality for virtualElements to this project. It'll still work with knockout-debug until I get a chance to fix it.

I've updated the links to a version of the JSBin that uses the `-debug` version, so will close this. But please let me know / reopen if I've missed the issue here. :)

Cheers

**Closed as completed by brianmhunt** 2015-02-12 15:48 UTC

**Comment by 4ver** [comment] 2015-02-12 20:05
Thanks, everything works perfectly now.
